I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/date1.rpy", line 14, in script
    if affection >= 50:
  File "game/date1.rpy", line 14, in <module>
    if affection >= 50:
NameError: name 'affection' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/date1.rpy", line 14, in script
    if affection >= 50:
  File "C:/Users\elain\Downloads\renpy-8.3.7-sdk/renpy/ast.py", line 1856, in execute
    if renpy.python.py_eval(condition):
  File "C:/Users\elain\Downloads\renpy-8.3.7-sdk/renpy/python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:/Users\elain\Downloads\renpy-8.3.7-sdk/renpy/python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/date1.rpy", line 14, in <module>
    if affection >= 50:
NameError: name 'affection' is not defined

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
Cadence of Love 1.0
Tue Apr 22 22:00:52 2025
